### PR TITLE
Updated icon

### LINKED ISSUE #42: [Request]: Follow GNOME HIG in App Icon
### Tell us the problem or your need

The App Icon does not fit gnome styling or human interface guidelines. The box around the bell is flat and unnecessary, and the bell is flat and longer than it should be, as the hig specifies:
> Avoid extreme aspect ratios for the icon shape, such as very narrow or very wide shapes.

### Describe the solution you'd like

Follow the GNOME [Human Interface Guidelines for App Icons](https://developer.gnome.org/hig/guidelines/app-icons.html)

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by edfloreshz**
This PR proposes a new icon for the app.

While making changes to it I realized that the icon worked better without a background:

image

Let me know your thoughts @dgsasha 

Closes #42

### CODE REVIEW

**Comment by dgsasha** [comment]
Let's discuss this here https://github.com/remindersdevs/Reminders/issues/42, along with the name change. I think the bell should be abandoned in the icon.

**Comment by edfloreshz** [comment]
I kinda like it, but sure, let's discuss there.

**Comment by dgsasha** [comment]
Closing because I've made my own icon, but thanks for the inspiration!

**Comment by edfloreshz** [comment]
No worries! I like the new icon 🎉

**Pull request closed without merging**
